version: "3.7"
services:

  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
    ports:
      - "8000:80"
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - SECRET_KEY=${SECRET_KEY}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - ROLLBAR_ENABLED=${ROLLBAR_ENABLED}
      - ROLLBAR_ENV=${ROLLBAR_ENV}
      - ROLLBAR_KEY=${ROLLBAR_KEY}
      - SMTP_TLS=${SMTP_TLS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - ZILLION_CONFIG=${ZILLION_CONFIG}
      - ZILLION_OPENAI_API_KEY=${ZILLION_OPENAI_API_KEY}
      - ZILLION_OPENAI_MODEL=${ZILLION_OPENAI_MODEL}
      - ZILLION_QDRANT_HOST=${ZILLION_QDRANT_HOST}
      - PRE_PRESTART_CMD=${PRE_PRESTART_CMD}
      - INITIAL_WAREHOUSES_FILE=${INITIAL_WAREHOUSES_FILE}
      - SQLALCHEMY_SILENCE_UBER_WARNING=1
      - PLUGIN_TOKEN=${PLUGIN_TOKEN}
      - PLUGIN_WAREHOUSE_ID=${PLUGIN_WAREHOUSE_ID}
      - PLUGIN_EMAIL=${PLUGIN_EMAIL}
      - PLUGIN_LEGAL_INFO=${PLUGIN_LEGAL_INFO}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - /volumes/qdrant:/qdrant/storage

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND}:${TAG-latest}'
    ports:
      - "80:80"
    environment:
      - VUE_APP_DOMAIN=${DOMAIN}
      - VUE_APP_NAME=${VUE_APP_NAME-Zillion}
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: ${FRONTEND_ENV-production}
        VUE_APP_DOMAIN: ${DOMAIN}
        VUE_APP_NAME: ${VUE_APP_NAME-Zillion}
