version: "3.7"
services:

  backend:
    stdin_open: true
    tty: true
    volumes:
      - ./backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN}
      - EMAIL_TEST_USER=${EMAIL_TEST_USER}
      - DEBUG=true
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # This command comes with the base image:
    command: /start-reload.sh

  frontend:
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: development
        VUE_APP_DOMAIN: localhost:8000
        VUE_APP_NAME: ${VUE_APP_NAME-Zillion}
