DEBUG: false
LOAD_TABLE_CHUNK_SIZE: 5000
ZILLION_DB_URL: ${SQLALCHEMY_DATABASE_URI}
ADHOC_DATASOURCE_DIRECTORY: /tmp

OPENAI_API_KEY: ${ZILLION_OPENAI_API_KEY}
OPENAI_MODEL: ${ZILLION_OPENAI_MODEL}
QDRANT_HOST: ${ZILLION_QDRANT_HOST}

DATASOURCE_QUERY_MODE: sequential
DATASOURCE_QUERY_TIMEOUT: 120
DATASOURCE_QUERY_WORKERS: 4
DATASOURCE_MAX_JOINS: null
DATASOURCE_MAX_JOIN_CANDIDATES: 50

DATASOURCE_CONTEXTS:
    baseball_data_bank:
      conn_url: ${SQLALCHEMY_DATABASE_URI}


