DEBUG: false
LOAD_TABLE_CHUNK_SIZE: 5000
ZILLION_DB_URL: ${SQLALCHEMY_DATABASE_URI}
ADHOC_DATASOURCE_DIRECTORY: /tmp

DATASOURCE_QUERY_MODE: sequential
DATASOURCE_QUERY_TIMEOUT: 120
DATASOURCE_QUERY_WORKERS: 4

DATASOURCE_CONTEXTS:
    baseball_data_bank:
      conn_url: ${SQLALCHEMY_DATABASE_URI}
    glide_covid_19:
      conn_url: ${SQLALCHEMY_DATABASE_URI}

