DEBUG: false
LOAD_TABLE_CHUNK_SIZE: 5000
ZILLION_DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}/${POSTGRES_DB}
ADHOC_DATASOURCE_DIRECTORY: /tmp

DATASOURCE_QUERY_MODE: sequential
DATASOURCE_QUERY_TIMEOUT: 120
DATASOURCE_QUERY_WORKERS: 4